name: "release"

on:
  push:
    branches: [release]

jobs:
  publish_package:
    uses: vodyani/workflows/.github/workflows/publish-npm-package.yml@master
    secrets:
      NPM_CI_TOKEN: ${{ secrets.NPM_CI_TOKEN }}
    with:
      enable_build: false

  publish_release:
    needs: [publish_package]
    uses: vodyani/workflows/.github/workflows/publish-release.yml@master
    secrets:
      GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
