name: "release"

on:
  push:
    branches: [master]

jobs:
  semantic_release:
    uses: vodyani/workflows/.github/workflows/semantic-release.yml@master
    secrets:
      NPM_CI_TOKEN: ${{ secrets.NPM_CI_TOKEN }}
      GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      enable_build: false
